<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '12.0.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'CB',
  'author' => 'Dev CB',
  'description' => 'Módulo custom A para casabaca',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'CasabacaMA',
  'published_date' => '2023-05-04 21:18:01',
  'type' => 'module',
  'version' => 1683235081,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'CasabacaMA',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'CB_ModuloA',
      'class' => 'CB_ModuloA',
      'path' => 'modules/CB_ModuloA/CB_ModuloA.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CB_ModuloA',
      'to' => 'modules/CB_ModuloA',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);